### ISSUE TITLE
add parts during writes?

### ISSUE THREAD

**Issue by jbenet** [connrs/node-sandwich-stream#2]
when using sandwich-stream in a pipeline, sometimes we need to add streams while writes have started. 

sandwich stream currently errors:

```
/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/multipart-stream/node_modules/sandwich-stream/lib/sandwich-stream.js:43
    throw new Error('SandwichStream error adding new stream while streaming');
          ^
Error: SandwichStream error adding new stream while streaming
    at Multipart.SandwichStream.add [as _add] (/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/multipart-stream/node_modules/sandwich-stream/lib/sandwich-stream.js:43:11)
    at Multipart.addPart (/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/multipart-stream/index.js:61:7)
    at writePart (/Users/jbenet/git/node-vinyl-multipart-stream/mp2v_flat.js:44:6)
    at Writable.w._write (/Users/jbenet/git/node-vinyl-multipart-stream/mp2v_flat.js:24:5)
    at doWrite (_stream_writable.js:290:12)
    at writeOrBuffer (_stream_writable.js:276:5)
    at Writable.write (_stream_writable.js:205:11)
    at Duplexify._write (/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/duplexify/index.js:200:22)
    at doWrite (/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jbenet/git/node-vinyl-multipart-stream/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:312:5)
```

**Comment by connrs** [comment]
Hey @jbenet,

I think that this would be a useful feature. It should be possible to alter this module so that it allows you to continue adding streams until the [stream has been closed](https://github.com/connrs/node-sandwich-stream/blob/0b5be8ab88c652d4539a496fbeaeccb328f34299/lib/sandwich-stream.js#L64): `this.push(null);`

I'm happy to take a pull request from you to add this feature if you're in a position to do it. I think that there should be a new variable to track whether the final stream has been emitted: `_streamEnded`. I think that this variable should replace `if (!this._streamsActive) {` on [line 36](https://github.com/connrs/node-sandwich-stream/blob/0b5be8ab88c652d4539a496fbeaeccb328f34299/lib/sandwich-stream.js#L36). After that, I think that we'd need 2 tests to replace the `Throws error if you add a stream while streaming` test.

I'm at the end of a 2 week holiday and will be returning to the office tomorrow. As a result, I'm very likely to be busy for a couple of weeks. If you're able to submit a pull request for this feature, I'll be happy to release it and publish an update for you.

Cheers,
Paul.

**Comment by connrs** [comment]
Marking as closed. The feature was added in #3 and version 2.0.0 is now available on npm
